import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";

const rajdhani = Rajdhani({ 
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-rajdhani'
});

export const metadata: Metadata = {
  title: "Tarun's portfolio",
  description: "Generated by Portfolio web",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rajdhani.className}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}